# Generated by Django 3.2.6 on 2021-08-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plate_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('dosage', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Beryllium.material')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beryllium.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Beryllium.patient')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Beryllium.tester')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='plate_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Beryllium.plate_type'),
        ),
        migrations.AddField(
            model_name='plate',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beryllium.test'),
        ),
    ]
