# Generated by Django 3.2.9 on 2021-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate_type',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
