# Generated by Django 3.2.6 on 2021-08-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='plate_Type',
            new_name='plate_type',
        ),
    ]
