# Generated by Django 3.2.6 on 2021-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0002_rename_plate_type_plate_plate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate_type',
            name='classification',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bikoret pha'), (2, 'bikoret pmw')], default=1),
        ),
    ]
