# Generated by Django 3.2.6 on 2021-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0003_plate_type_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate_type',
            name='classification',
            field=models.PositiveSmallIntegerField(choices=[(1, 'test'), (2, 'control')], default=1),
        ),
    ]
