# Generated by Django 3.2.6 on 2021-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0004_alter_plate_type_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='unitOfMeasure',
            field=models.CharField(default='mg', max_length=20),
        ),
    ]
