# Generated by Django 3.2.6 on 2021-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0007_well_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='num',
            new_name='numInPlate',
        ),
        migrations.AddField(
            model_name='well',
            name='numInTest',
            field=models.IntegerField(null=True),
        ),
    ]
