# Generated by Django 3.2.6 on 2021-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beryllium', '0008_auto_20210903_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='column',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
